-- Enable the pg_trgm extension for search (optional but recommended)
create extension if not exists "pg_trgm";

-- Create a table for profiles (optional, links to auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS) for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- Create a table for posts/articles
create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text, 
  featured_image text,
  status text default 'draft' check (status in ('draft', 'published', 'archived')),
  published_at timestamp with time zone,
  author_id uuid references auth.users(id) default auth.uid()
);

-- Set up RLS for posts
alter table posts enable row level security;

-- Policy: Everyone can read published posts
create policy "Published posts are viewable by everyone." on posts
  for select using (status = 'published');

-- Policy: Authenticated users can see all posts (for admin dashboard)
create policy "Authenticated users can see all posts." on posts
  for select using (auth.role() = 'authenticated');

-- Policy: Authenticated users can insert posts
create policy "Authenticated users can insert posts." on posts
  for insert with check (auth.role() = 'authenticated');

-- Policy: Authenticated users can update posts
create policy "Authenticated users can update posts." on posts
  for update using (auth.role() = 'authenticated');

-- Policy: Authenticated users can delete posts
create policy "Authenticated users can delete posts." on posts
  for delete using (auth.role() = 'authenticated');

-- STORAGE POLICIES (Run these after creating the 'images' bucket)
-- We insert the bucket into storage.buckets if it does not exist
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- Then run these to allow authenticated uploads.

-- Allow public read access to the bucket
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'images' );

-- Allow authenticated users to upload
create policy "Authenticated users can upload images"
on storage.objects for insert
with check ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- Allow authenticated users to update their own images (or all if admin)
-- Allow authenticated users to update their own images (or all if admin)
create policy "Authenticated users can update images"
on storage.objects for update
using ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- ANALYTICS TABLE
create table analytics (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  page text not null,
  country text,
  city text,
  device text,
  ip_hash text -- optional, for unique visitor counting without storing raw IP
);

alter table analytics enable row level security;

-- Allow public (anon) to insert logs (record visits)
create policy "Public can insert analytics" on analytics
  for insert with check (true);

-- Allow admins (authenticated) to view logs
create policy "Admins can view analytics" on analytics
  for select using (auth.role() = 'authenticated');

